### ISSUE TITLE
Ensure that all bech32 prefixes are registered in Satoshi Labs repo

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#101]
https://github.com/satoshilabs/slips/blob/master/slip-0173.md

**Comment by JeremyParish69** [comment]
Most seems to be good, but I found some that aren't up to date:

Missing from SLIP173:
- [ ] bitcanna
- [ ] comdex
- [ ] crescent
- [ ] cronos
- [ ] firmachain
- [ ] impacthub (pending merge)
- [ ] lumnetwork
- [ ] nomic
- [ ] umee

Added to SLIP173 but mismatching:
- [ ] galaxy
- [ ] irisnet
- [ ] likecoin

**Comment by JeremyParish69** [comment]
Not only are all these chains' prefixes registered and identical in SLIP173, but now there is a data validation script as an on-PR GitHub action that throws exception when bech32 prefix isn't yet registered. This should be sufficient to prevent registrations from disagreeing or being incomplete..
