### ISSUE TITLE
Script to convert Terra's tokens.js list into an assetlist

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#105]
https://github.com/terra-money/assets/blob/master/cw20/tokens.js

**Comment by JeremyParish69** [comment]
This was done once when #343 was merged, and by now Terra is virtually irrelevant. A scriupt that does this may still apply to Terra 2.0 or other chains, but for now we can probably close this.

**Comment by sunnya97** [comment]
Agreed
