### ISSUE TITLE
Does SLIP44 Require Array?

### ISSUE THREAD

**Issue by JeremyParish69** [cosmos/chain-registry#1077]
Currently, SLIP44 accepts a single number. But some chains apparently support multiple coinTypes. (e.g., Persistence supporting ~750 and also 118, and now Mises also supporting both 60 and 118.

I'm thinking that SLIP44 property might need to change from a number to an array.

From: `"SLIP44": 118`
To:

```
"coinTypes": [
  60,
  118
],
```

**Comment by JeremyParish69** [comment]
Will note that Keplr's and Leap's Suggest Chain feature accepts a required primary coinType with optional alternatives:
```
"bip44": {
  "coinType": "number"
},
"alternativeBIP44s": [
  "items": {
    "type": "number"
  }
]
```
Persistence example:
```
"bip44": {
  "coinType": 118
},
"alternativeBIP44s": [
  750
]
```

**Comment by JeremyParish69** [comment]
Another option is to make sure the submitter knows about the SLIP44 registration process (something often forgotten):
```
"bip44": {
  "coinType": 118,
  "SLIP44_coin": "Atom"
},
"alternativeBIP44s": [
  {
    "coinType": 750,
    "SLIP44_registration": "Persistence"
  }
]
```
...but that kind of looks more messy than it is beneficial, if if it does permit very clean automated verification.

**Comment by JeremyParish69** [comment]
Another alternative is to keep the original SLIP44 property, and just add an optional altSLIP44 array:
```
SLIP44: 118,
altSLIP44s: [
  750
]
```

it saves from having to restructure the SLIP44 field, and avoids a potentially breaking change.

**Comment by pyramation** [comment]
yea I think this works.

My only thought is more broad now, which is this `snake_case` in JSON is starting to show it's face 😅
