### ISSUE TITLE
Validation Error logo_URIs

### ISSUE THREAD

**Issue by social244305-Architect** [cosmos/chain-registry#1176]
I am trying to add API/RPC for Fetch and Stride chain.json but Stride chain.json is failing validation with following error.

{'path': 'stride/chain.json', 'errors': [<ValidationError: "Additional properties are not allowed ('logo_URIs' was unexpected)">]}

I see "logo_URIs" in definition but not in properties. Is this a problem with schema? See PR #1174 for error.

**Comment by JeremyParish69** [comment]
Apologies, and thanks for pointing this out. 'logo_URIs' and 'keywords' were supposed to be under properties--not $defs. Working on a fix. Should be able to reopen your PR.
