### ISSUE TITLE
Proposal for changing structure of the repo

### ISSUE THREAD

**Issue by liangping** [cosmos/chain-registry#1217]
The current directory structure is a little messy, I suggest an adjustment, so that the hierarchy and scalability are better, create a new "mainnet" directory, it is recommended to move all chain directories to "mainnet",
The adjusted top structure is roughly as follows:
*.schema.json
IBC/
nonIBC/
mainnets/
testnets/
README
...

**Comment by greg-szabo** [comment]
Is this a duplicate of #444? If yes, please make your comments there and we can close this one.
