### ISSUE TITLE
missing grpc endpoint

### ISSUE THREAD

**Issue by marbar3778** [cosmos/chain-registry#127]
Grpc provides functionality to easily create clients that show all possible queries and possible msg types supported by a chain. As the cosmos ecosystem has adopted grpc already it would be best to include it into the chain registry. 

Example: 
![photo_2021-12-29 23 32 31](https://user-images.githubusercontent.com/24299864/147751258-32dc6027-e6e6-498c-ba80-fdc554df8399.jpeg)

This would help with building tools like lens from Strangelove 

cc @sunnya97

**Comment by sunnya97** [comment]
There's a field for it in the schema (https://github.com/cosmos/chain-registry/blob/master/chain.schema.json#L143), and some of the chains have it (i.e. https://github.com/cosmos/chain-registry/blob/master/regen/chain.json#L58).  I just don't have this data for most of the chains.

**Comment by marbar3778** [comment]
ah okay missed it in  the few chains I looked at.
