### ISSUE TITLE
Make it clear what the native staking token is

### ISSUE THREAD

**Issue by nooomski** [cosmos/chain-registry#139]
Right now, fee and/or staking tokens are listed in two places:

1. under fees in chain.json
2. in assetlist.json

However, there's a possibility that some chains use a different token for fees than for staking. Should we make it clear what the native staking token is? And if so, in which file? Assetlist.json mentions it in the description, but we should probably just have a specific field for that. What do y'all think?

**Comment by hxrts** [comment]
interchain security will have different gov vs staking token as well

**Comment by nooomski** [comment]
Perhaps we should include a `type` field for each asset in assetlist.json that can contain either one or more of `fee`, `governance`, `staking` and `ibc`.

**Comment by mccallofthewild** [comment]
Proposed solutions for this in https://github.com/cosmos/chain-registry/issues/126

**Comment by nooomski** [comment]
My bad! Will close this. Thanks!
