### ISSUE TITLE
how to future proof tendermint_version key?

### ISSUE THREAD

**Issue by doggystylez** [cosmos/chain-registry#1517]
cosmos-sdk has already replaced tendermint as a dependency with [cometbft](https://github.com/cometbft/cometbft)

**Comment by JeremyParish69** [comment]
generalize somehow?
e.g., `consensus: "tendermint 0.3"` `consensus: "cometbft 2.0"`

**Comment by doggystylez** [comment]
perhaps an array like

<pre>...
"consensus": [
  "type": "tendermint",
  "version": "0.34"
],
...</pre>

**Comment by JeremyParish69** [comment]
I like that. 
minor detail, but instead of an array, should be an object?
...
"consensus": {
  "type": "tendermint",
  "version": "0.34"
},
...
