### ISSUE TITLE
Fix low gas price to 0.0025 in osmosis 

### ISSUE THREAD

**Issue by Rodrigoberes24** [cosmos/chain-registry#1806]
The v15 upgrade implements [Osmosis Proposal 354](https://www.mintscan.io/osmosis/proposals/354), which sets a minimum gas price of 0.0025 uOSMO at the protocol-level.

https://github.com/cosmos/chain-registry/blob/master/osmosis/chain.json#L22

source

https://medium.com/osmosis-community-updates/osmosis-v15-0-0-sodium-upgrade-abb02767283d

**Comment by dylanschultzie** [comment]
@Rodrigoberes24 added a PR, thanks!
