### ISSUE TITLE
Chronic Chain seems to be dead. Can someone confirm?

### ISSUE THREAD

**Issue by webmaster128** [cosmos/chain-registry#1887]
See https://github.com/cosmos/chain-registry/blob/master/chronicnetwork/chain.json

- All endpoints unreadable
- All repos archived: https://github.com/ChronicNetwork
- Last article Aug 2022: https://medium.com/@chronicchain

I think the `status` should be changed.

**Comment by staking-explorer** [comment]
Seems its live: https://api-chronic.zenchainlabs.io/cosmos/base/tendermint/v1beta1/blocks/latest

**Comment by staking-explorer** [comment]
But we also added this chain to BL in our project because of instability...

**Comment by webmaster128** [comment]
Thank you for the info. Since the chain produces blocks, I'll close my issue for now.

If anyone has further information about the status of the project, feel free to reopen.
