### ISSUE TITLE
Set a License?

### ISSUE THREAD

**Issue by atharen** [cosmos/chain-registry#2154]
I know this might sound petty but does it make sense to give the repo a license?

Since it is not really code, maybe a [Creative Commons License](https://creativecommons.org/about/cclicenses/) is apt?

Probably `CC0`, `CC BY`, or `CC BY-SA` are the relevant ones...

_[Had also posted this on tg](https://t.me/c/1888994636/181)._

**Comment by atharen** [comment]
Personally, from what I gather, I see the Public Domain `CC0` License makes the most sense...

**Comment by atharen** [comment]
@JeremyParish69 brought up a [good point on tg](https://t.me/c/1888994636/188):

> I think a license is probably a good idea, but I hope someone with more experience with them can comment

For now, I opted to [ping the top 5 contributors](https://github.com/cosmos/chain-registry/graphs/contributors), as they all seem to have significant and frequent contributions, which at least might be able to take are representative choice.

- @JeremyParish69 
- @dylanschultzie 
- @sunnya97 
- @doggystylez 
- @tombeynon

[Creative Commons license chooser](https://chooser-beta.creativecommons.org/) makes this kind of blunt, but from my impression this project seems to either warrant having an [_all rights granted_ with public domain](https://creativecommons.org/publicdomain/), or to at least [attribute this specific effort](https://creativecommons.org/licenses/by/4.0/) (i.e. mention that this project was used, and any changes made).

---

Tbh, I did find this project from a fork, but with an no license it sort of implies this effort is subject to copyright, with ramifications dependent on each jurisdiction (i.e. kind of ambiguous), which typically means strong copyright, [whose affect](https://choosealicense.com/no-permission/) seem not aligned with this project's goals...

_Willing to open a PR once a decision is made._

**Comment by ValarDragon** [comment]
Agreed that `CC0`, `CC BY` or `CC BY SA` are the relevant ones.

I feel like this being `CC BY` sgtm

**Comment by atharen** [comment]
Thanks @JeremyParish69! 
_Closing issue..._
