### ISSUE TITLE
cosmos.directory / main json should use image logo's from chainlist.json, not assetlist.json

### ISSUE THREAD

**Issue by PFC-developer** [cosmos/chain-registry#2617]
if you have a look @ migaloo, it has images defined in the chainlist.json,  but https://chains.cosmos.directory/ appears to use the images from the assetlist in it's 'image' field, causing incorrect logos (the first coin, not the chain logo).

TIA
PFC

**Comment by dylanschultzie** [comment]
@PFC-developer to clarify, you want a change within the cosmos directory? https://github.com/eco-stake/cosmos-directory

**Comment by PFC-developer** [comment]
yes.. placed the issue over there.. thanks @dylanschultzie
