### ISSUE TITLE
logos for chains

### ISSUE THREAD

**Issue by hxrts** [cosmos/chain-registry#265]
looks like we have asset logos, but it came up in relayer chat that they needed _chain_ logos for something. typically the chain logo = the staking token logo, but this doesn't have to be the case. staking and governance tokens can also be distinct, as will be the case for v1 Interchain security.

would be good to accomodate svg + png versions and annotate image type.

**Comment by JeremyParish69** [comment]
what if we put in the chain.json file logo_URIs { png: , svg: } ?
Although we may want to allow for more images, for now, this at least allows for a chain logo in a familiar format.
