### ISSUE TITLE
Missing `image` field on https://chains.cosmos.directory

### ISSUE THREAD

**Issue by jo-chainmasters** [cosmos/chain-registry#2877]
Hey friends,
since i updated the registry about the Unification Blockchain, Unification is not showing on ReStake.
I digged into it and found the following:
ReStake is showing only 122 of 132 Networks on the Startpage. After debugging i know they showing network only if the `image` field of a network has data.
Yes, its maybe an issue of the ReStake UI, but i debugged a little more and found the following:
According due to the chain schema and assetlist schema there is no field `image`. Only an array `images`. I guess `image` is something from the past.
But if i check https://chains.cosmos.directory/ the `images` array is not served. So there is no chance for other projects to get the image paths.
For a lot of networks and assets `image` is served, but not for Unification because i dont filled that field because its not in the schema.
I will raise a ticket at ReStake too because it makes no sense to not display a Network if no logo is served. But i think we should start at the registry to clean the situation. I can understand that `image` will be served (down compatibility), but `images` should be served too i think?. (Otherwise it makes no sense to have it in the schema).

Or maybe its an issue with aggregation of the data? Maybe `image` is auto-generated and depends on anything which is missing in the Unification chain JSON?

**Comment by JeremyParish69** [comment]
Yes for the time being we should maintain the logo_URIs property that most systems are used to querying. Images will have advanced capability but the logo_URIs property should still remain

**Comment by JeremyParish69** [comment]
This should be resolved now?
https://github.com/cosmos/chain-registry/pull/2883

**Comment by JeremyParish69** [comment]
Yes, for now we'll make sure any usage of `images` also has the `logo_URIs` property as well. Interfaces can continue to pull directly from the `logo_URIs` property and `images` will only be used to inform scripts to make updates to the `logo_URIs` property where appropriate.

**Comment by JeremyParish69** [comment]
Seems to be resolved
