### ISSUE TITLE
Cosmos Directory web endpoint

### ISSUE THREAD

**Issue by tombeynon** [cosmos/chain-registry#289]
I recently built https://cosmos.directory which is an open source UI and API around the Chain Registry. It makes it easy to integrate Chain Registry data into any application via JSON APIs, and carries out various status checking of the public APIs for stability. It also provides CORS supported proxy endpoints for web applications. 

I noticed ping.pub has just done something similar with chain registry data and this has been added to the Chain Registry readme. I wanted to ask if cosmos.directory would be appropriate to mention here as well?

REStake.app uses cosmos.directory to provide all the interchain functionality so it's in use in production, but it's new so it's still evolving. 

API docs etc on the README https://github.com/eco-stake/cosmos-directory

**Comment by nooomski** [comment]
This is amazing. Happy to add this to the readme!
See #293 

Thanks so much!!

**Comment by tombeynon** [comment]
Awesome, I wasn't aware of some of those projects but they're great! Appreciate it
