### ISSUE TITLE
Add unbonding periods to chains so relayers can set trust_periods

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#29]

**Comment by nooomski** [comment]
I like this, but how do we make sure this is updated after a governance proposal changes the param? Responsibility of chain.json maintainers?

**Comment by JeremyParish69** [comment]
> I like this, but how do we make sure this is updated after a governance proposal changes the param? Responsibility of chain.json maintainers?

Is this something the lens tool could verify? and then have a script to submit a change if needed?

**Comment by JeremyParish69** [comment]
What should be the unit of duration? It probably goes technically always goes by number of blocks, but we'll probably also want an estimated time duration. And in what units should that time be? I suppose day is common enough, but we may end up having to change to hour, and seconds would be best unit with very high precision. Shoul.d it be a number with assumed unit? Or allow for a regex'd string? or some kind of datetime format?

I might propose: 
```
"staking": {
  "staking_tokens": [
    {
      "denom": "uatom",
      "mininim_lock_duration": {
        "blocks": 12345678,
        "approx_time": "15 days"
      }
    }
  ]
}
```

why did I put the duration inside the staking token object? same reason as why the staking tokens is an array and not a single denom: in case different tokens have different locking durations.
E.g., ION staking is not for the chain, but might be nice to be able to record that here.

**Comment by JeremyParish69** [comment]
Should we change the entire staking section to look like this?
`osmosisd q staking params`
```
bond_denom: uosmo
historical_entries: 10000
max_entries: 7
max_validators: 118
min_commission_rate: "0.050000000000000000"
min_self_delegation: "0"
unbonding_time: 1209600s
```
