### ISSUE TITLE
Wrong RPC for Injective (Polkachu)

### ISSUE THREAD

**Issue by shifty11** [cosmos/chain-registry#304]
@PolkachuIntern

It seems that there is a copy/paste error in the injective configuration.
This is the `chain.json` of injective:
```
"apis": {
        "rpc": [
            {
                "address": "https://agoric-rpc.polkachu.com",
                "provider": "Polkachu"
              }
        ],
```
I guess it should be `https://injective-rpc.polkachu.com` and not `agoric`

**Comment by PolkachuIntern** [comment]
Thanks. Fix it with this PR https://github.com/cosmos/chain-registry/pull/305
