### ISSUE TITLE
Sentinel incorrect slip44

### ISSUE THREAD

**Issue by tombeynon** [cosmos/chain-registry#313]
The Chain Registry [defines Sentinel](https://github.com/cosmos/chain-registry/blob/671e8c8cb69265d9d1156005c3eb3fb31a741d57/sentinel/chain.json#L9) as having a `slip44` of `750`.

[Based on this issue](https://github.com/eco-stake/restake/issues/463) that's not what Keplr is configured for, and Sentinel is supported natively so it's not a `suggestChain` issue. Keplr uses `118` I believe.

I'm not connected with Sentinel but can anyone confirm which is correct?

**Comment by JeremyParish69** [comment]
Sentinel team confirms they use 118 CoinType. Osmosis code also defines Sentinel's CoinType as 118, which is working correctly. Looking for confirmation that there are no other CoinTypes being used before updating SLIP44.
