### ISSUE TITLE
Add archive nodes to chain registry

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/chain-registry#33]
Archive nodes should be added as an item to the chain registry.

**Comment by jackzampolin** [comment]
I've added a couple of mine to the RPC section

**Comment by JeremyParish69** [comment]
archive boolean added to endpoint object in https://github.com/cosmos/chain-registry/pull/454
is this suggestion asking for precisely that? Or is there anything else, like an 'archive nodes' array or something?
Otherwise, I'd like to close this issue

**Comment by ValarDragon** [comment]
That suffices for this, thanks!
