### ISSUE TITLE
Nomic binary shown with the link to Akash

### ISSUE THREAD

**Issue by mgialong215** [cosmos/chain-registry#392]
https://github.com/cosmos/chain-registry/blob/master/nomic/chain.json

**Comment by nooomski** [comment]
Hi @mgialong215 thanks for raising this. Afaik they don't have their binaries listed yet, correct? Couldn't find any under releases.

**Comment by mgialong215** [comment]
ah yes. They are using develop branch to compile. Will reopen when their is one available.
