### ISSUE TITLE
Include Tendermint and SDK version

### ISSUE THREAD

**Issue by nooomski** [cosmos/chain-registry#40]
`tendermint_version`
`sdk_version`

**Comment by ValarDragon** [comment]
Should be `tendermint_minor_version`, and `sdk_minor_version` at most, but these can be pulled from a script from `compatible_versions`. The patch versions will be different depending on the compatible version used

**Comment by nooomski** [comment]
Ah right, thanks for the correction!

**Comment by marbar3778** [comment]
Think there should be a script to populate most of the needed data. 

Like I open a PR that adds, rpc, rest, grpc and the script uses this endpoint to get version, chain-name peers and so on. The script can run periodically to see if anything changes, this avoids needing to update everything manually

**Comment by JeremyParish69** [comment]
When I look on explorers, I see stuff like SDK: v0.45.3 . Are you suggesting @ValarDragon to get rid of the 0 to only go up by minor version (45, 46 etc.)? wouldn't that just complicate things and require extra string processing to do comparisons?

I liked the idea of something like:
`cosmos_sdk_version: 0.45.3`
`tendermint_version: 0.34.12`

I wonder if we can use something like Lens with a script to grab this info for all the chains....

Also, is it better to prefix it with a 'v'? like `v0.45.3`?

**Comment by ValarDragon** [comment]
I'm suggesting trimming the patch version, due to compatible versions being a list, which can have different patch versions on each.

I generally think the dev UX of requiring users to run an extra command to auto-populate fields isn't great. I guess if we had a daily commit to main that syncs generated fields, that would make sense

**Comment by JeremyParish69** [comment]
we could use an 'x' to denote that the patch is to not be used? Or should that just be omitted entirely? (wouldn't want something thinking that they should include the patch version)

I'll assume for now we can omit the 'v'?

`cosmos_sdk_version: 0.45.x`
`tendermint_version: 0.34.x`
