### ISSUE TITLE
Inconsistent GenesisL1 chain.json file name

### ISSUE THREAD

**Issue by vlad-blana** [cosmos/chain-registry#407]
All the other chain dirs have the file named 'chain.json' not 'chain**s**.json'.
There seems to be a naming convention in the project, based on the Readme, schema and actual file names, which was not used in the genesisl1 case.
It may break stuff in the future.

**Comment by JeremyParish69** [comment]
Thank you for pointing this out, it was merely a typo. I thought this would have been could by checks....
