### ISSUE TITLE
Add cosmwasm to chain.json?

### ISSUE THREAD

**Issue by JeremyParish69** [cosmos/chain-registry#419]
Add cosmwasm to chain.json? This can help establish a set of features for Keplr::Suggest Chainlist.

Could do something like:
`"cosmwasm_version": 0.24`
or
`"cosmwasm_enabled": true` 

How to we find the version of comswasm a chain is using? or How do we find what the latest version of cosmwasm is?

Do we need to allow listing a specific set of features?

Should this go under the codebase object in chain.json?

**Comment by JeremyParish69** [comment]
I believe the suggestion from @nooomski is to use a single field to specify either the cosmwasm version or that there's no cosmwasm at all. e.g.,:
`"cosmwasm_version": false,`
or
`"cosmwasm_version": 0.24`

**Comment by JeremyParish69** [comment]
perhaps @ankurdotb you might have thoughts on this...

**Comment by ankurdotb** [comment]
I would suggest doing a `cosmwasm_enabled` as a boolean true/false, as well as version number. The edge case I'm thinking of is in case a chain ships with a CosmWasm binary as a positioning change but doesn't actively use it. If that's _too_ much of an edge case, then just a `cosmwasm_version` is fine, but may be extensible in the future to specific CosmWasm features enabled under that version.

**Comment by mccallofthewild** [comment]
@JeremyParish69 @ankurdotb This is a good idea but vm-specific metadata shouldn't be top level in the chain schema. Operate on the assumption that all chains will implement IBC.
 
 I would support something like this
```json
{
  [...]
  "contract_environments": [
    {
      "permissionless": false,
      "virtual_machine": "evm",
      "version": "v0.13.2"
    }
  ]
  [...]
}
```
where `virtual_machine` is an enum/union of
```
"cosmwasm" | "evm" | "zoe" | "gno" | ...
```

**Comment by JeremyParish69** [comment]
@ValarDragon says: "...[cosmowasm_enabled] will later need to be an enum to encapsulate permissioned"
