### ISSUE TITLE
Standardize on an automated json chains can maintain

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/chain-registry#425]
Its silly that chain developers have to make a PR to this repo for every release they do.

instead, we should make the chain.json include a url to a chain schema file on the chain's repository, and we have a github bot daily submit commits to keep them in sync.

The chain repo's schema file should maintain `recommended_version`, `compatible_version` and `binaries`.

In the future, perhaps we add more items. 

This feels like it should be relatively light to do. The current format feels untenable.

**Comment by ValarDragon** [comment]
Ah conveniently for now, this is literally the codebase field:

```
  "codebase": {
    "git_repo": "https://github.com/osmosis-labs/osmosis",
    "recommended_version": "v10.0.0",
    "compatible_versions": ["v10.0.0"],
    "binaries": {
      "linux/amd64": "https://github.com/osmosis-labs/osmosis/releases/download/v10.0.0/osmosis-10.0.0-linux-amd64",
      "linux/arm64": "https://github.com/osmosis-labs/osmosis/releases/download/v10.0.0/osmosis-10.0.0-linux-arm64"
    }
 ```
 
So then we should just add a field for 'schema', that such a bot can query

**Comment by ValarDragon** [comment]
The bot should be something that daily:
1) Looks for the schema url in each chain supported
2) Tries downloading latest from each chains URL
3) Checks if for every chain there is a difference
4) If theres a difference, make a single commit doing all the updates to a new branch
5) open a PR for that branch to main.

Perhaps once its demonstrated it works well, we drop the PR step, and let it commit directly to main.

0) github action that runs daily: https://jasonet.co/posts/scheduled-actions/
1) can be done by some pretty straightforward json parsing in any language
2) should be straightforward in any language
3) should be straigfhtforward in any language
4) https://github.com/marketplace/actions/add-commit
5) heres how you make a PR: https://github.com/marketplace/actions/github-action-for-creating-pull-requests

**Comment by ValarDragon** [comment]
My recommendation for how to start on this:
* First make a github action that runs manually
* First step checkout main
* Then call into a python script
* The python script runs steps (1), (2), (3)
* Use linked github actions for (4) & (5)

Then make it on a schedule.

**Comment by xBalbinus** [comment]
Awaiting write permissions to make a PR.

**Comment by xBalbinus** [comment]
The successful run: https://github.com/xBalbinus/chain-registry/actions/runs/2536132975
Created PR: https://github.com/xBalbinus/chain-registry/pull/1
