### ISSUE TITLE
CORS error when fetching https://raw.githubusercontent.com/cosmos/chain-registry/master/andromeda1/assetlist.json

### ISSUE THREAD

**Issue by jaan1025** [cosmos/chain-registry#4346]
<img width="635" alt="image" src="https://github.com/cosmos/chain-registry/assets/22076610/9d969601-d8d5-42e7-af38-8ad9b7e97d2d">

**Comment by ankurdotb** [comment]
This was likely either temporary due to an issue with Github, or an extension that's causing this issue. Github seems to be returning `access-control-allow-origin: *` so it shouldn't throw CORS errors

**Comment by JeremyParish69** [comment]
I believe the answer above provides sufficient explanation.
