### ISSUE TITLE
Aptos type is labeled as evm-base

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#4528]
Aptos type is labeled as evm-base, but it's not an EVM as far as I'm aware. 

https://github.com/cosmos/chain-registry/blob/eadb5fa2acad607eb779d57a835b664f29f98dd5/_non-cosmos/aptos/assetlist.json#L20

**Comment by JeremyParish69** [comment]
This has been changed to type `unknown`. As communities grow more types can be added. 
https://github.com/cosmos/chain-registry/blob/0260a8e654869f723ee3f85194bae04192dc5f65/_non-cosmos/aptos/assetlist.json#L20
