### ISSUE TITLE
Allow for chain and asset KEYWORDS?

### ISSUE THREAD

**Issue by JeremyParish69** [cosmos/chain-registry#461]
Adding keywords could make searching for certain chains and assets could make dApp usage more effective.

The idea comes from [an Issue submitted on Osmosis Assetlist](https://github.com/osmosis-labs/assetlists/issues/96).

Add keywords array to chain.json keywords for the chain, and another within each asset in assetlist.json.

Example use cases:
- e.g., searching 'terra' could point you to USTC, KRTC, LUNC, LUNA, ANC, MIR, etc., because 'terra' would be a keyword for both terra blockchains, but also foremost a keyword for USTC and KRTC.
- Searching for old names on things could show assets. e.g., 'switcheo' can show assets from Carbon chain. Searching for 'matic' can show Polygon assets.
- searching for chain ids could show assets from the related chain, e.g., colombus for terra classic, or phoenix for terra2
- searching for utility could result in certain assets. e.g., searching 'cloud' could result in Akash assets. 'staked atom' could result in PSTAKE.  'NFTs' from STARS and MNTL. 'stable' for USTC, USDC, DAI, EEUR, etc.

Perhaps there should be limitations to this. How do we make sure chains don't spam their keyword list with a million popular unrelated terms just to try to show up first on every search? Should we put a limit to the number of keywords, say, 20 words?

e.g.,
for Secret Network:
`"keywords": {"privacy", "secret", "sefi", "SCRT", "sSCRT", "snip", "snip20", "supernova", "sienna", "shade"}`

**Comment by pyramation** [comment]
as `keywords` is also a feature in npm `package.json` files, seems like a pretty standard field we should include. Totally agree.

**Comment by sunnya97** [comment]
I like "keywords" 👍
