### ISSUE TITLE
Missing Logo

### ISSUE THREAD

**Issue by briangarden** [cosmos/chain-registry#4853]
Hey team, the logo of Joltify chain is missing after the sucessful merge of our PR in chain registry repo.
Could you please take a look into this issue so that we can get required file ready and uploaded.
Link: https://cosmos.directory/joltify

Much thanks.

**Comment by JeremyParish69** [comment]
It seems the images have been registered correctly. I believe the issue by now is likely that cosmos directory is only looking at logo_URIs, and not `images`. Cosmos Directory team should update their app to look at the `images` property.
