### ISSUE TITLE
Add `historical_version_matrix` to Chain registry 

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/chain-registry#521]
We need to store historical version history for chains, to easily be able to sync from genesis to latest tip. (And will likely be of benefit for archive node querying)

I suggest in the codebase section, we add a `historical_versions` key, which takes in a list of objects of the form:
```
{
  height: {height}
  upgradename: {upgrade name}
  upgradeBranch: {git tag}
}
```

Then we can change all syncing scripts to use chain registry

**Comment by JeremyParish69** [comment]
Think this is similar to Unity's issue https://github.com/cosmos/chain-registry/issues/130

**Comment by ValarDragon** [comment]
Can we add this for osmosis? Cc @czarcas7ic if we have the height version numbers handy, then we can start getting genesis sync scripts against this

**Comment by czarcas7ic** [comment]
@ValarDragon 
Start on v3
v4: 1314500
v5: 2383300 (can use v6 binary here)
v6: 2464000
v7: 3401000 (can use v8 binary here)
v8: 4402000
v9: 4707300 (can use v10 binary here)
v10: 4713065
v11: 5432450

**Comment by ValarDragon** [comment]
OK sweet! Let's cut out the v5, v7, v9 releases

**Comment by czarcas7ic** [comment]
@ValarDragon actually it would have to be the opposite right? We would have to cut out the v6, v8, and v10 releases because nodes syncing should upgrade to the next higher binary pre fork.

**Comment by ValarDragon** [comment]
Err specify v5 height, v6 code, etc. For each

**Comment by sunnya97** [comment]
Maybe let's just give chain upgrades a single name, not a list of names.
