### ISSUE TITLE
Remove the $ in front of {txHash} in explorer urls

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#58]
I don't know why it's there, and seems to cause issues

@Thunnini do you know if we still need it?

**Comment by Thunnini** [comment]
Substituting {txHash} is not standard in Javascript, I just need it, so I roughly made it work. I don't care if there is a $ or not.

**Comment by sunnya97** [comment]
Actually it seems that this is a standard in JS, so maybe we keep this

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

What's odd is that the Keplr Suggest chain doesn't strip the dollar sign
