### ISSUE TITLE
Historical versions, change names to have an official on-chain name

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/chain-registry#659]
In #521 , we changed the schema to make names a list.

A bit annoying, is that in the cosmos SDK there is a notion of "official upgrade name", which you need for configuring cosmovisor.

I think we should we switch to:
* code_upgrade_name
* display_upgrade_name (optional)
(Or something to this extent)

**Comment by sunnya97** [comment]
Maybe let's just give chain upgrades a single name, not a list of names.

**Comment by ValarDragon** [comment]
That SGTM
