### ISSUE TITLE
should we enforce testnets have unique names?

### ISSUE THREAD

**Issue by pyramation** [cosmos/chain-registry#679]
```
    "chain_name": "cheqd",
```

appears in both main and testnets...

the problem is that assetlist has no way of telling if network_type is mainnet or testnet. I would suggest instead of adding network_type to assetlist, we try to enforce testnets are named uniquely from the mainnet name.

**Comment by pyramation** [comment]
related https://github.com/cosmos/chain-registry/pull/680

**Comment by JeremyParish69** [comment]
Yes, I think so.
I also am considering whether the folder titles should be the corresponding mainnet folder name + "testnet". So, e.g., kujira's testnet should have a folder and chainname of kujiratestnet/, but the pretty_name can be "harpoon".

**Comment by JeremyParish69** [comment]
I believe this has been enforced to all existing testnet folders and would be simple to maintain
