### ISSUE TITLE
add `additionalProperties: false` to schemas

### ISSUE THREAD

**Issue by pyramation** [cosmos/chain-registry#735]
https://github.com/cosmos/chain-registry/blob/350840e766f7574a120760a13eda4c466413308a/testnets/stateset/assetlist.json#L24

**Comment by pyramation** [comment]
if we were to allow this, we could edit the schema. However, not sure we should from a graphics quality perspective.

**Comment by JeremyParish69** [comment]
currently, there's something missing from most objects in the schema definitions, which is `"additionalProperties": "false"` . Once this is added ubiquitously throughout the schema (all objects), we should then stop seeing undefined properties, such as this 'jpeg'. On my todo list.

as for allowing jpegs, I actually think that should be fine.

**Comment by pyramation** [comment]
ah that makes sense! We should add `additionalProperties: false` to nearly everything. 

I know endpoints is one area, but still I think there is away to allow any key, but enforce the child schema. E.g. `grpc-web` maybe is not explicit in the schema, but the children `{ endpoints, archive, provider }` would be enforced.

**Comment by pyramation** [comment]
I renamed the issue to focus on the root cause, if there is another, let's close this one.
