### ISSUE TITLE
Define mininum-gas-prices parameter

### ISSUE THREAD

**Issue by dylanschultzie** [cosmos/chain-registry#768]
It might make sense to define a minimum_gas parameter that copies the recommended minimum as defined by the various networks. 

As an example, Juno's is: `"0.0025ujuno,0.001ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9"` https://docs.junonetwork.io/validators/joining-mainnet#set-minimum-gas-prices.

Kujira's is:
`"0.00119ukuji,0.00150ibc\/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F,0.000125ibc\/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2,0.00126ibc\/47BD209179859CDE4A2806763D7189B6E6FE13A17880FE2B42DE1E6C1E329E23,0.00652ibc\/3607EB5B5E64DD1C0E12E07F077FF470D5BC4706AFCBC98FE1BA960E5AE4CE07,617283951ibc\/F3AA7EF362EC5E791FE78A0F4CCC69FEE1F9A7485EB1A8CAB3F6601C00522F10,0.000288ibc\/EFF323CC632EC4F747C61BCE238A758EFDB7699C3226565F7C20DA06509D59A5,5ibc\/DA59C009A0B3B95E0549E6BF7B075C8239285989FF457A8EDDBB56F10B2A6986,0.00137ibc\/A358D7F19237777AF6D8AD0E0F53268F8B18AE8A53ED318095C14D6D7F3B2DB5,0.0488ibc\/4F393C3FCA4190C0A6756CE7F6D897D5D1BE57D6CCB80D0BC87393566A7B6602,78492936ibc\/004EBF085BBED1029326D56BE8A2E67C08CECE670A94AC1947DF413EF5130EB2,964351ibc\/1B38805B1C75352B28169284F96DF56BDEBD9E8FAC005BDCC8CF0378C82AA8E7\"`

The cardinal benefit for this will be with `relayers` as they will be able to better know what given gas prices are.

**Comment by dylanschultzie** [comment]
`fees` might be what I'm referring to: https://github.com/cosmos/chain-registry/blob/master/chain.schema.json#L77

but it seems like not? It seems like a Keplr integration param.

**Comment by JeremyParish69** [comment]
It sounds like you're describing the fees::fee_tokens::fixed_min_gas_price (which exists). I don't see how this doesn't hold the same information

**Comment by dylanschultzie** [comment]
@JeremyParish69 it does, for sure, I just didn't see it used on first perusal.
