### ISSUE TITLE
Running list of non-added chains

### ISSUE THREAD

**Issue by sunnya97** [cosmos/chain-registry#79]
A list of chains who need more metadata added because they are missing or are only stubs right now.

- [x] Sommelier
- [x] Injective
- [x] IrisNet (is Stub)
- [x] Band Chain
- [x] Switcheo
- [x] Fetch.ai
- [x] Omniflix
- [x] Ryzon
- [x] Odin Network
- [x] Vidulum
- [x] Chihuahua
- [x] Dig Chain
- [x] Konstellation Network

**Comment by JeremyParish69** [comment]
Generally, all these once-stubs have been completed. With improved schema validation on python checks, stubs should be much less likely to appear going forward.
