### ISSUE TITLE
Should the chain-registry also store 'suggestchain' data?

### ISSUE THREAD

**Issue by web3-nomad** [cosmos/chain-registry#978]
right now it feels like a bit of a hit or miss on this kind of info.
and I've seen a few suggest chains on various sites that are either out of data, or just plain wrong (and screw it up for interoperability across wallets)

(not sure if this is the right forum for this though)

**Comment by JeremyParish69** [comment]
Could you be more specific what you mean by suggestchain data here? If it is what I think it is, we might already be in the works for a solution.

**Comment by JeremyParish69** [comment]
Closing due to lack of further discussion
